# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            John Wilhoite
tagline:          ''
description:      "PhD Candidate in Economics, University of Virginia" 
url:              "https://jwilhoite.github.io"
baseurl:          ""


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/jwilhoite/jwilhoite.github.io/
